kind: Service
apiVersion: v1
metadata:
  labels:
    app: {{ .Release.Name }}
    type: {{ .Values.loadbalancerService.type }}
  name: {{ .Values.loadbalancerService.name }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: http
    port: 15672
    protocol: TCP
    targetPort: 15672
  - name: amqp
    port: 5672
    protocol: TCP
    targetPort: 5672
  selector:
    {{- include "rabbitmq-cluster.selectorLabels" . | nindent 4 }}
  type: {{ .Values.loadbalancerService.type }}
