kind: Secret
apiVersion: v1
metadata:
  name: rmq-cluster-secret
  namespace: {{ .Release.Namespace }}
stringData:
  cookie: ERLANG_COOKIE
  password: {{ .Values.rabbitmqPass.password | quote }}
  url: amqp://{{ .Values.rabbitmqPass.username }}:{{ .Values.rabbitmqPass.password }}@{{ .Values.loadbalancerService.name }}
  username: {{ .Values.rabbitmqPass.username }}
type: Opaque
